remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme

title: Amol Satdive
description: Research Portfolio | CFD | Turbulence | High-Performance Scientific Computing

markdown: kramdown
kramdown:
  math_engine: mathjax
